### ISSUE TITLE
MENU - identification des rubriques sélectionnées

### ISSUE THREAD

**Issue by nadarizkallah** [manufacture-dev/manufacture-dev.github.io#24]
Ca serait pas mal d'avoir la couleur de la page visitée qui se change quand on navigue sur le site. 
Car on ne sait pas sur quelle page on est après avoir cliqué (ex : je lis la page offre, je ne vois pas visuellement sur le menu que je suis sur cette page). 
Je sais que le trait de couleur sous le nom de la page que Romain nous avait suggéré était difficilement faisable techniquement.
Why not changer la couleur du mot en orange pour indiquer la page en cours?

![image](https://user-images.githubusercontent.com/94697437/143432643-94b693b4-4fd3-44ad-a568-5641c2ae067e.png)

**Comment by jlrigau** [comment]
Je ne pense pas que le trait de couleur soit si insurmontable
