### ISSUE TITLE
Add missing titles on section for offer page

### ISSUE THREAD

**Issue by jlrigau** [manufacture-dev/manufacture-dev.github.io#25]
With the new rearrangement of the offer page some section have missing title ⬇️

**Comment by jlrigau** [comment]
<img width="1330" alt="Screenshot 2021-11-25 at 13 51 50" src="https://user-images.githubusercontent.com/274281/143445084-18d43c6b-b7ef-4d60-ad95-4861548ef481.png">

**Comment by jlrigau** [comment]
<img width="1270" alt="Screenshot 2021-11-25 at 13 52 19" src="https://user-images.githubusercontent.com/274281/143445147-fff1c767-d3fa-4a69-a3c1-9403cc0ee7bc.png">

**Comment by jlrigau** [comment]
<img width="1206" alt="Screenshot 2021-11-25 at 13 52 38" src="https://user-images.githubusercontent.com/274281/143445193-cef97c82-6063-4fbf-bee7-a19fd766f09e.png">

**Comment by nadarizkallah** [comment]
Sur la version du PPTX du 05/11 j'avais mis des titres pour chacune des sections, ce que finalement tu as préféré retirer.
![image](https://user-images.githubusercontent.com/94697437/143478202-3c0185b8-87cd-4ed6-bcd4-b44f68523d21.png)

![image](https://user-images.githubusercontent.com/94697437/143478228-694646b1-21c0-4873-8966-6ccec28c10e4.png)

![image](https://user-images.githubusercontent.com/94697437/143478275-e7673c88-db2d-4cdd-9b1f-e23378b55d70.png)

![image](https://user-images.githubusercontent.com/94697437/143478300-24bfbd33-3b79-4fc5-8abc-d7d507e258ba.png)
