### ISSUE TITLE
Mobile - offre - espacer les 3 rectangles et on voit des petits carrés en filigrane dans le fond, à quoi c'est du?

### ISSUE THREAD

**Issue by nadarizkallah** [manufacture-dev/manufacture-dev.github.io#50]
![image](https://user-images.githubusercontent.com/94697437/144701778-31721435-0382-4030-accf-a09e2b4afad7.png)

**Comment by jlrigau** [comment]
https://github.com/manufacture-dev/manufacture-dev.github.io/issues/14
